name = "MusicProcessing"
uuid = "32bb9398-a9ad-408c-b137-8304ef5cbed9"
repo = "https://github.com/JuliaMusic/MusicProcessing.jl.git"
version = "1.8.1"

[deps]
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
DSP = "0.6.10, 0.7"
Documenter = "0.27"
FFTW = "1.3"
FixedPointNumbers = "0.8"
IntervalSets = "0.5, 0.7"
Requires = "1.1"
Unitful = "1.7"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
